version: '3.4'
services:
  ethchain-geth.public.dappnode.eth:
    image: 'ethchain-geth.public.dappnode.eth:10.0.40'
    build: ./build
    volumes:
      - 'ethchain-geth:/root/.ethereum/ethchain-geth'
    environment:
      - EXTRA_OPTS=
    ports:
      - '443:443'
      - '8546:8546'
      - '8545:8545'
      - '30303:30303'
      - '30303:30303/udp'
volumes:
  ethchain-geth: {}
