version: '3.4'
services:
  ethchain-geth.public.dappnode.eth:
    image: 'ethchain-geth.public.dappnode.eth:10.0.4'
    build: ./build
    volumes:
      - 'ethchain-geth:/root/.ethereum/ethchain-geth'
    environment:
      - EXTRA_OPTS=
    ports:
      - '127.0.0.1:8546:8546'
      - '127.0.0.1:8545:8545'
      - '61313:30303'
      - '61313:30303/udp'
      - '61314:30304/udp'
volumes:
  ethchain-geth: {}